export enum Pain {
  NO_PAIN = 'NO_PAIN',

  DISCOMFORTING = 'DISCOMFORTING',

  DISTRESSING = 'DISTRESSING',

  INTENSE = 'INTENSE',

  UTTERLY_HORRIBLE = 'UTTERLY_HORRIBLE',

  UNIMAGINABLE = 'UNIMAGINABLE',
}
